### ISSUE TITLE
[BUG] APM data including Transactions, Spans, CPU and Memory metrics are not sent when CPU utilization over 60%

### ISSUE THREAD

**Issue by kbalys** [elastic/apm-agent-dotnet#1571]
I've recently updated apm .net core plugin from version 1.7.1 to 1.11.1 and after update I see metrics like this picture below. Other APM data (e.g. transactions) seem to be sent correctly.
![image](https://user-images.githubusercontent.com/67997608/141996196-9254810a-dc9e-42b6-ba5b-b1c5a73cdc4d.png)

### APM Agent version
1.11.1+ca11381c8840632c65925393de57797871b359c5

### Environment
Docker, Elastic Cloud, APM 7.14

**.NET Framework/Core name and version** 
NET Core 3.1.21
**Application Target Framework(s)** netcoreapp3.1

### Describe the bug
Metrics are not sent to Elasticsearch. I don't however see rejections in the APM service so my guess is that they are not sent from agent.

### To Reproduce
I don't have steps for reproduce now, I will work on the sample. It looks that when CPU utilization is high the queue of metric events doesn't flush as frequently as possible but this is only mu guess. I have set "MetricsInterval": "10s" in config.

#### Expected behavior
The metrics are continues lines.

#### Actual behavior
Metrics are not reported when they CPU above 60%.

**Comment by gregkalapos** [comment]
Hi @kbalys, 

experimenting with the `MetricsInterval` is definitely a good idea - let us know if that changes anything, or you see any pattern with that.

Another thing that comes to my mind is that in `1.11.0` we introduced the "Time spent by span type" metrics - so that's an additional metrics which the agent collects. You can disable it by adding `span.self_time` to the [`DisableMetrics` config](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-reporter.html#config-disable-metrics) - could you maybe check if that makes any difference?

As the last thing, it'd be also useful to look at [agent logs](https://www.elastic.co/guide/en/apm/agent/dotnet/current/config-supportability.html#config-log-level) - first on warning level, then set it to debug and finally to trace (debug and trace will likely generate even more overhead, so that could influence the test... nevertheless those detailed logs could be very useful).

**Comment by kbalys** [comment]
Hi @gregkalapos, 

I will investigate this more, however cannot reproduce it locally yet. 
When it comes to MetricsInterval I have this set to 10s in production.

The Time spent by span is working correctly the same as transaction data. See below the same timeframe, data seems to be consistent.
![image](https://user-images.githubusercontent.com/67997608/142010588-726cf4fa-eea9-4642-9151-1897d752c24c.png)
![image](https://user-images.githubusercontent.com/67997608/142010845-c9b05977-f4b6-4d3a-83a8-db0d53b8d774.png)

**Comment by skuc-fp** [comment]
Hi, after some investigation we managed to create a sample app with reproduction of the bug:
[MissingMetrics.zip](https://github.com/elastic/apm-agent-dotnet/files/7641196/MissingMetrics.zip) (our credentials were redacted from appsettings.json)

We have determined the reason for the missing metrics is thread starvation.
In the sample app we use this code to execute background task:
```
ThreadPool.QueueUserWorkItem<object>(
                    callBack: s => ConsumeSingleCore(percentage, cancellationToken), 
                    state: null, 
                    preferLocal: false);
```
With the `preferLocal` parameter set to false (which is default in some of the `QueueUserWorkItem` method overloads) the metrics are missing when CPU usage is high. However, when the parameter is set to true, we don't observe this behavior:
![image](https://user-images.githubusercontent.com/61985321/144406650-116adcbc-adab-4e68-8209-ef15069c76c1.png)

To simulate high CPU usage we created CpuBurner class (present in the sample app) and burned CPU with 100 threads, 95% usage for 60 seconds.
We tried setting log level for APM to Trace, but as soon as we start burning the CPU all logging stops.

Disabling `span.self_time` makes no difference.
LMK if I can provide more information to help alleviate this issue.

**Comment by kbalys** [comment]
Hi @gregkalapos, have you managed to reproduce the issue? Is any quick workaround possible?

Please let me know if you need more details.

**Comment by skuc-fp** [comment]
HI, @gregkalapos, any news on this issue?

**Comment by kbalys** [comment]
Hi All, @gregkalapos, 

I think this issue is **more serious than I thought at first time**. Not only metrics are not delivered but also other data such as transactions and spans. Please compare the following two charts:
AWS load balancer statistics:
![image](https://user-images.githubusercontent.com/67997608/150321749-f7440ae5-4dc3-4902-98ba-fd258b5c6020.png)
with 

Whereas what I see in APM is: 
![image](https://user-images.githubusercontent.com/67997608/150322060-2594fada-a3b4-4b50-bbbe-e34fd70e0ca7.png)

The throughput shape for transactions in APM seems be be cut when CPU usage reaches its peak times. AWS diagram correctly depicts anticipated shape. 

This is **very serious problem** as it looks like APM transaction data sent by plugin is **not reliable**.

**Comment by skuc-fp** [comment]
I have created another project with reproduction, this time with minimal amount of code extracted from the agent, mainly **BackendCommComponentBase** and **SingleThreadTaskScheduler**.
You can observe that when we start burning CPU all logging almost completely stops.
[ElasticIsFantastic.zip](https://github.com/elastic/apm-agent-dotnet/files/7950864/ElasticIsFantastic.zip)

**Comment by kbalys** [comment]
Hi @gregkalapos, have you managed to reproduce the issue? Do you need anything more from us? 

After our investigation we think the problem is thread pool starvation and the thread which sends apm data to server executes some async task which cannot run or complete if system is very busy and there are no free threads in thread pool. If we set ThreadPool.SetMinThreads(Int32, Int32) to high value or use preferLocal for thread pool QueueUserWorkItem, the metrics are sent correctly. However, in real application which uses a lot of libraries we cannot usually change it

Ideally, the apm should use dedicated thread to execute its sending logic so we can get metrics and transaction also under a very high load.

**Comment by gregkalapos** [comment]
Thanks for the reproducer - super useful, I see the problem locally as well.

> Ideally, the apm should use dedicated thread to execute its sending logic so we can get metrics and transaction also under a very high load.

That was the original goal, which clearly isn't the case anymore. I'll try to rewrite this part to make sure we use 1 dedicated thread.

**Comment by kbalys** [comment]
Hi @gregkalapos, 

do you have any update regarding this issue? We desperately need a fix for it. Is it possible to prioritize it?

**Comment by gregkalapos** [comment]
https://github.com/elastic/apm-agent-dotnet/pull/1670 made a change which'd fix the threading issue - with that PR, sending data will happen on a dedicated thread (as it should have been anyway).

That fix will be in the next release - I don't know when exactly the release happen, but it should be soon.

I keep this open to track if it fixed the issue or not.

**Comment by kbalys** [comment]
Hi @gregkalapos, 

do you possibly know when the next release is planned?

**Comment by gregkalapos** [comment]
We just released a version which includes a PR that addresses this issue: https://github.com/elastic/apm-agent-dotnet/releases/tag/v1.15.0

Could someone maybe give it a try and let me know if the situation improved?

**Comment by kbalys** [comment]
Hi @gregkalapos, 

thank you for the release. Unfortunately, I have bad news. The 1.15 release doesn't solve the issue. Please see my diagram below. On the left 1.11.1 version and 1.15 on the right - the same problem is still there. Tested with agent:
agent.version - 1.15.0+03d5f13cfbcb431ef0ee7cec6c88734dbf6d7540


![image](https://user-images.githubusercontent.com/67997608/169292685-c22e791f-688b-4954-96f0-2256b7bfa7e8.png)

**Comment by gregkalapos** [comment]
Closing now - feel free to reopen.

**Comment by kbalys** [comment]
Unfortunately, still not working on 1.17.

![image](https://user-images.githubusercontent.com/67997608/193142635-ea153dcc-1a98-4571-bf5f-4f5f3076bba0.png)

![image](https://user-images.githubusercontent.com/67997608/193142758-1545b1c1-079d-4fa1-92d9-a25ca38bbb6d.png)

**Comment by kbalys** [comment]
@gregkalapos I don't see an option to reopen this one, should I create a new issue?
